[package]
name = "Foo"
version = "0.1.0"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "b334b19e42c7a4512fe76f29fdda9303dfb0e112"

[addresses]
foo = "0x7c0ead33b66551bf7189957a3998b2c9ced7b6e6"
